### ISSUE TITLE
Build error installing the library

### ISSUE THREAD

**Issue by iferrant** [Upstarts/editor.js-kit-android#20]
### Description
Following the **Installation** section of the README leads me to an error synchronizing the project with Gradle.

### Steps to reproduce
- Add maven repository to the project Gradle file:
```
maven { url "https://dl.bintray.com/heckslam/EditorJSKit" }
```
- Add library to the app Gradle file (current release 2.0.0):
```
implementation 'com.github.upstarts:ejkit:2.0.0
```
- Sync project with Gradle files

### Error description
Android Studio produces the following error:
```
Could not GET 'https://jitpack.io/com/github/upstarts/ejkit/2.0.0/ejkit-2.0.0.pom'. Received status code 401 from server: Unauthorized
```

**Comment by Upstarts** [comment]
@heckslam mind to have a look, please?

**Comment by heckslam** [comment]
hello. you can take a look at the updated README. It was republished to jitpick

**Comment by Upstarts** [comment]
Issue resolved
