### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by Dambakk** [Upstarts/editor.js-kit-android#6]
Hi!

This project is able to render links, but nothing happens when they are clicked. Do I have to configure something to make links clickable or is this not supported yet?

Thanks.

**Comment by Dambakk** [comment]
I see that the underlying TextView has `android:autoLink="web"` and `android:linksClickable="true"` but nothing happens when clicked. (Cloned the project and ran it with the example dummy json)

**Comment by Dambakk** [comment]
I modified your example app according to this SO post and links now open as expected! https://stackoverflow.com/a/4303608/5892676 

If I create a pull request, when can I expect it to be merged?

**Comment by heckslam** [comment]
thanks for creating the issue. It was fixed in 0.0.9
